basic_settings:
  site_title: Hexa Studios
  favicon_image: /images/favicon.png

header_settings:
  logo_image: 
  logo_width: 100

menu_settings:
  menu_items:
    - title: 'Projects'
      url: '/'
    - title: 'Blog'
      url: '/blog/'

footer_settings:
  logo_image: 
  logo_width: 100
  tagline: Developers delivering bespoke solutions

hero_settings:
  background_image: /images/backgrounds/hexa-background-hero2.png

post_settings:
  grid_spacing: 10

contact_settings:
  email_address: 'mat@hexastudios.co'
  form_action: 'https://formspree.io/f/xoqkqjpv'
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Get in Touch'

social_settings:
  facebook_url: 'https://facebook.com/hexastudiosco'
  twitter_url: 'https://twitter.com/hexa_studios'
  instagram_url: 'https://instagram.com/matloughnane'
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: 'https://play.google.com/store/apps/dev?id=4783590797014052198'
  tumblr_url: ''
  dribbble_url: 'https://dribbble.com/matloughnane'
  behance_url: ''
  deviantart_url: ''
  github_url: ''
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: ''

color_settings:
  background_color: '#ffffff'
  background_alt_color: '#f4f5f6'
  text_dark_color: '#202224'
  text_medium_color: '#6C7A89'
  text_light_color: '#AEB3BB'
  accent_color: '#498a47'
  secondary_accent_color: '#6F1E51'
  border_color: '#ECEDEF'
  error_color: '#D64541'

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css?family=Josefin+Sans:400,500,700|Lato:400,700" rel="stylesheet">'
  title_font: '"Josefin Sans", sans-serif'
  body_font: 'Lato, sans-serif'
  regular_weight: 400
  bold_weight: 700
  site_title:
    small_size: 30
    medium_size: 40
    large_size: 45
    weight: 700
    letter_spacing: -0.02
  menu:
    small_size: 30
    medium_size: 15
    large_size: 17
    weight: 600
    letter_spacing: 0
  h1:
    size: 52
    size_small: 42
    weight: 700
    letter_spacing: -1.5
    letter_spacing_small: -1.2
    line_height: 64
    line_height_small: 48
  h2:
    size: 48
    size_small: 36
    weight: 700
    letter_spacing: -1.6
    letter_spacing_small: -1.04
    line_height: 48
    line_height_small: 42
  h3:
    size: 40
    size_small: 30
    weight: 700
    letter_spacing: -1.4
    letter_spacing_small: -0.54
    line_height: 48
    line_height_small: 36
  h4:
    size: 32
    size_small: 28
    weight: 700
    letter_spacing: -1
    letter_spacing_small: -0.6
    line_height: 36
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  subtitle:
    size: 22
    size_small: 20
    weight_regular: 400
    weight_heavy: 500
    letter_spacing: 0.16
    letter_spacing_small: 0.2
    line_height: 32
    line_height_small: 28
  p:
    size: 18
    size_small: 17
    weight: 400
    letter_spacing: 0.04
    letter_spacing_small: 0
    line_height: 28
  p_small:
    size: 16
    size_small: 15
    weight: 400
    letter_spacing: 0
    line_height: 24
  label:
    size: 14
    small_size: 12
    weight: 500
    letter_spacing: 0.8
    small_letter_spacing: 0.5
    line_height: 16
  footnote:
    size: 13
    weight: 400
    letter_spacing: -0.04
    line_height: 12
  blockquote:
    small_size: 22
    medium_size: 28
    large_size: 32
    weight: 500
    letter_spacing: -0.02
    line_height: 1.3
  buttons:
    weight: 500
    letter_spacing: 0.4

advanced_settings:
  ajax_loading: true
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""